version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - webnet
  nextjs:
    build: .
    environment:
      - NODE_ENV=production
    networks:
      - webnet
networks:
  webnet:
