version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - webnet
  nextjs:
    build: .  # Look for a Dockerfile in the current directory
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
      - /app/node_modules  # Ensures node_modules are not overwritten by the host's node_modules
    environment:
      - NODE_ENV=production
    networks:
      - webnet
networks:
  webnet:
